INSERT INTO users (name, blacklisted, "createdAt", "updatedAt") VALUES
('Dương Thuỳ An', false, NOW(), NOW()),
('Võ Văn Lê Dũng', false, NOW(), NOW()),
('Lê Thị Duyên', false, NOW(), NOW()),
('Nguyễn Văn Dưỡng', false, NOW(), NOW()),
('Lê Xuân Đạt', false, NOW(), NOW()),
('Lê Thị Hiền', false, NOW(), NOW()),
('Lê Thị Thu Hiền', false, NOW(), NOW()),
('Nguyễn Văn Hiếu', false, NOW(), NOW()),
('Lê Huy Hoàng', false, NOW(), NOW()),
('Bùi Công Hùng', false, NOW(), NOW()),
('Hoàng Kim Hưng', false, NOW(), NOW()),
('Hoàng Văn Khánh', false, NOW(), NOW()),
('Nguyễn Thị Kim Lan', false, NOW(), NOW()),
('Dương Thị Linh', false, NOW(), NOW()),
('Dương Thị Thuỳ Linh', false, NOW(), NOW()),
('Nguyễn Hoàng Long', false, NOW(), NOW()),
('Lê Thị Thảo Ly', false, NOW(), NOW()),
('Trần Thị Ni Na', false, NOW(), NOW()),
('Nguyễn Văn Nam', false, NOW(), NOW()),
('Nguyễn Duy Nghĩa', false, NOW(), NOW()),
('Lương Văn Ngọc', false, NOW(), NOW()),
('Võ Trương Bảo Ngọc', false, NOW(), NOW()),
('Lê Đức Nguyễn', false, NOW(), NOW()),
('Nguyễn Thị Hà Nhi', false, NOW(), NOW()),
('Nguyễn Hồng Quân', false, NOW(), NOW()),
('Nguyễn Thành Quân', false, NOW(), NOW()),
('Nguyễn Thị Lệ Quyên', false, NOW(), NOW()),
('Lê Văn Sỹ', false, NOW(), NOW()),
('Nguyễn Văn Tài', false, NOW(), NOW()),
('Nguyễn Thị Thanh Tâm', false, NOW(), NOW()),
('Trần Thị Mỹ Tâm', false, NOW(), NOW()),
('Nguyễn Xuân Thịnh', false, NOW(), NOW()),
('Lê Thị Thu Thuý', false, NOW(), NOW()),
('Phạm Anh Thư', false, NOW(), NOW()),
('Nguyễn Đình Tiến', false, NOW(), NOW()),
('Nguyễn Thị Ngọc Tính', false, NOW(), NOW()),
('Lê Thuỳ Trang', false, NOW(), NOW()),
('Lê Thị Hồng Trinh', false, NOW(), NOW()),
('Đinh Thị Ánh Tuyết', false, NOW(), NOW()),
('Phạm Thị Tươi', false, NOW(), NOW()),
('Hoàng Văn Vũ', false, NOW(), NOW()),
('Nguyễn Ngọc Vũ', false, NOW(), NOW()),
('Lê Võ Sang Xuân', false, NOW(), NOW()),
('Đinh Ngọc Như Ý', false, NOW(), NOW());
